import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtempSync,mkdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import net from 'node:net';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium:pw}=require('playwright');
const project=dirname(dirname(fileURLToPath(import.meta.url))),base=project,db=join(mkdtempSync(join(tmpdir(),'cs-browser-')),'test.sqlite3');
const probe=net.createServer();await new Promise(resolve=>probe.listen(0,'127.0.0.1',resolve));
const port=probe.address().port,baseURL=`http://127.0.0.1:${port}`;
await new Promise(resolve=>probe.close(resolve));
const server=spawn('python',['-m','carbonshift','--db',db,'app','--port',String(port)],{cwd:project,env:{...process.env,ELECTRICITYMAPS_API_KEY:'',CARBONSHIFT_OBSERVATIONS:db+'.jsonl',CARBONSHIFT_ASSETS:db+'-assets'}});
let output='';server.stdout.on('data',b=>output+=b);server.stderr.on('data',b=>output+=b);
let browser;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
try{
 let ready=false;
 for(let i=0;i<100;i++){try{const r=await fetch(baseURL+'/health');if(r.ok){ready=true;break;}}catch{} await pause(100);}
 assert(ready,'launcher failed: '+output);
 browser=await pw.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(baseURL);
 await page.waitForFunction(()=>document.querySelector('#reduction').textContent==='76%');
 await page.waitForFunction(()=>document.querySelector('#connection').textContent==='Local API connected');
 assert(await page.locator('#run-button').isDisabled());
 assert.equal(await page.locator('#forecast-chart svg').count(),1);
 await page.waitForFunction(()=>document.querySelector('#carbon-key-status').textContent.includes('Set ELECTRICITYMAPS_API_KEY'));
 assert(await page.locator('#carbon-fetch').isDisabled());
 const noKey=await page.request.post(baseURL+'/api/carbon/observe');
 assert.equal(noKey.status(),503);
 const now=new Date(),past=new Date(now-4*3600000);
 const reading={source:'electricitymaps',zone:'IN-WE',carbon_intensity_gco2e_per_kwh:540.5,data_at:past.toISOString(),retrieved_at:now.toISOString(),is_estimated:true,estimation_method:'BROWSER_TEST_FIXTURE',stale:true,stale_after_seconds:10800,used_for_scheduling:false};
 await page.route('**/api/carbon/observations',route=>route.fulfill({json:{configured:true,records:[reading],total_valid_records:1,warnings:[]}}));
 await page.route('**/api/carbon/observe?**',route=>route.fulfill({status:503,json:{detail:'Rate limit (browser fixture)'}}));
 await page.evaluate(()=>loadObservations());
 assert.match(await page.locator('#carbon-latest').textContent(),/STALE SAVED READING/);
 assert.match(await page.locator('#carbon-latest').textContent(),/Provider-estimated/);
 await page.locator('#carbon-fetch').click();
 await page.waitForFunction(()=>document.querySelector('#carbon-message').textContent.includes('previous saved observation'));
 assert.match(await page.locator('#carbon-latest').textContent(),/540.5/);
 const carbonExport=page.waitForEvent('download');await page.locator('#carbon-export').click();assert.equal((await carbonExport).suggestedFilename(),'carbonshift-observations.json');
 await page.unroute('**/api/carbon/observations');await page.unroute('**/api/carbon/observe?**');
 await page.evaluate(()=>{document.getElementById('carbon-message').textContent='';return loadObservations();});
 mkdirSync(join(project,'screenshots'),{recursive:true});
 await page.screenshot({path:join(project,'screenshots/dashboard-desktop.png'),fullPage:true});
 await page.locator('[name=scenario]').selectOption('no-solar');
 assert(await page.locator('#export-plan').isDisabled());
 await page.locator('#optimize-button').click();
 await page.waitForFunction(()=>document.querySelector('#reduction').textContent==='0%');
 assert.equal(await page.locator('#baseline-time').textContent(),await page.locator('#recommended-time').textContent());
 await page.locator('[name=scenario]').selectOption('sunny');
 await page.locator('[name=objective]').selectOption('hybrid');
 await page.locator('#optimize-button').click();
 await page.waitForFunction(()=>!document.querySelector('#carbon-legend').hidden);
 const downloadPromise=page.waitForEvent('download');await page.locator('#export-plan').click();const download=await downloadPromise;
 assert.equal(download.suggestedFilename(),'carbonshift-plan.json');
 // Stub only worker readiness to exercise submission/cancellation with the real
 // HTTP API and SQLite. No container execution is claimed by this browser check.
 await page.route('**/api/system',async route=>{
  const response=await route.fetch(),data=await response.json();
  data.execution_ready=true;data.worker={state:'ready',online:true,at:Date.now()/1000,age_seconds:0};
  await route.fulfill({response,json:data});
 });
 await page.locator('[name=delay_seconds]').fill('60');
 await page.locator('[name=mode]').selectOption('solar-shift');
 await page.locator('#preview-run').click();
 await page.waitForFunction(()=>!document.querySelector('#run-button').disabled);
 assert.match(await page.locator('#execution-preview').textContent(),/60 seconds/);
 await page.locator('#run-button').click();
 await page.waitForFunction(()=>document.querySelector('#job-dialog').open);
 assert.match(await page.locator('#detail-content').textContent(),/SCHEDULED/);
 await page.locator('#cancel-job').click();
 await page.waitForFunction(()=>document.querySelector('#detail-content .badge').textContent==='CANCELLED');
 assert(await page.locator('#cancel-job').isHidden());
 const exported=page.waitForEvent('download');await page.locator('#export-job').click();assert.match((await exported).suggestedFilename(),/^carbonshift-job-/);
 await page.locator('#close-dialog').click();
 await page.unroute('**/api/system');
 await page.waitForFunction(()=>document.querySelector('#worker-label').textContent.includes('Docker needs attention'));
 await page.locator('[name=objective]').selectOption('solar');
 await page.locator('#optimize-button').click();
 await page.waitForFunction(()=>document.querySelector('#reduction').textContent==='76%');
 // Image batch: real upload, frozen preview, queue and cancellation. Readiness only is stubbed.
 await page.locator('#workload-choice').selectOption('images');
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAoAAAAHgCAIAAAC6s0uzAAAHZElEQVR4nO3VMQHAIADAMEAI6pCD6LmgxxIF/Tr3PQMAeGvVAQDwRwYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAgYMAAEDBgAAgYMAAEDBoCAAQNAwIABIGDAABAwYAAIGDAABAwYAAIGDAABAwaAgAEDQMCAASBgwAAQMGAACBgwAAQMGAACBgwAAQMGgIABA0DAgAEgYMAAEDBgAAh82PYEzq8FyYMAAAAASUVORK5CYII=','base64');
 await page.locator('#image-files').setInputFiles(Array.from({length:10},(_,i)=>({name:`photo-${i+1}.png`,mimeType:'image/png',buffer:png})));
 await page.locator('[name=scenario]').selectOption('no-solar');
 await page.locator('#image-timing').selectOption('earliest');
 await page.locator('#optimize-button').click();
 await page.waitForFunction(()=>document.querySelector('#image-review-content').textContent.includes('10 images'));
 assert(await page.locator('#queue-images').isDisabled());
 await page.route('**/api/system',async route=>{const response=await route.fetch(),data=await response.json();data.execution_ready=true;data.worker={state:'ready',online:true,at:Date.now()/1000,age_seconds:0};await route.fulfill({response,json:data});});
 await page.waitForFunction(()=>!document.querySelector('#queue-images').disabled);
 await page.locator('#image-quality').fill('75');
 assert(await page.locator('#queue-images').isDisabled());
 await page.locator('#optimize-button').click();
 await page.waitForFunction(()=>!document.querySelector('#queue-images').disabled);
 await page.locator('#queue-images').click();
 await page.waitForFunction(()=>document.querySelector('#job-dialog').open);
 assert.match(await page.locator('#detail-content').textContent(),/Image batch results/);
 assert.match(await page.locator('#detail-content').textContent(),/SCHEDULED/);
 await page.locator('#cancel-job').click();
 await page.waitForFunction(()=>document.querySelector('#detail-content .badge').textContent==='CANCELLED');
 // Explicit UI fixture: backend transform/download is covered separately by Python tests.
 const completed=await page.evaluate(()=>structuredClone(currentJob));
 completed.state='SUCCEEDED';completed.progress={processed:10,total:10};completed.exit_code=0;
 completed.evidence={runtime_seconds:1,artifact:{report:{processed:10,input_bytes:10000,output_bytes:5000,processing_seconds:0.8,files:[{original_name:'<script>fixture.png',output_name:'001.jpg',width:128,height:96,output_bytes:500}]}}};
 const detailURL=`**/api/jobs/${completed.id}`;
 await page.route(detailURL,route=>route.fulfill({json:completed}));
 await page.evaluate(id=>loadJob(id),completed.id);
 assert.equal(await page.locator('#detail-content progress').getAttribute('value'),'10');
 assert.equal(await page.locator('#detail-content script').count(),0);
 assert.match(await page.locator('#detail-content').textContent(),/Download processed images/);
 await page.route(`**/api/jobs/${completed.id}/results`,route=>route.fulfill({contentType:'application/zip',headers:{'Content-Disposition':'attachment; filename="ui-fixture.zip"'},body:Buffer.from('explicit browser download fixture')}));
 const outputDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Download processed images'}).click();
 assert.equal((await outputDownload).suggestedFilename(),'ui-fixture.zip');
 await page.unroute(detailURL);await page.unroute(`**/api/jobs/${completed.id}/results`);
 await page.locator('#close-dialog').click();
 await page.unroute('**/api/system');
 await page.waitForFunction(()=>document.querySelector('#worker-label').textContent.includes('Docker needs attention'));
 await page.locator('#optimize-button').click();
 await page.waitForFunction(()=>document.querySelector('#image-status').textContent.includes('Docker worker'));
 await page.screenshot({path:join(project,'screenshots/dashboard-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:join(project,'screenshots/dashboard-mobile.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile page overflow');
 assert.deepEqual(errors,[]);
 console.log('Image batch, live carbon panel and browser checks passed: scenarios, provenance, export, offline readiness, real HTTP queue/cancel with readiness stub, mobile width, no JS errors.');
 writeFileSync(join(project,'screenshots/browser-results.json'),JSON.stringify({passed:true,errors,real_docker_tested:false,readiness_stubbed_for_submission:true},null,2));
}finally{
 if(browser)await browser.close();
 server.kill('SIGINT');
 await Promise.race([new Promise(resolve=>server.once('exit',resolve)),pause(8000)]);
 if(server.exitCode===null)server.kill('SIGTERM');
 console.log('Launcher output:',output);
}
